#include "eglext_loader.h"

#include <stdlib.h>
#include <string.h>

#define LOAD_FUNCTION(TYPE, NAME) functions.NAME = (TYPE)eglGetProcAddress(#NAME)
#define IMPLEMENT_FUNCTION(TYPE, DEFAULT, NAME, ARGS...) \
    TYPE result = DEFAULT;                               \
    if (functions.NAME != NULL)                          \
    {                                                    \
        result = functions.NAME(ARGS);                   \
    }                                                    \
    return result

struct eglext_functions
{
    PFNEGLCREATESYNC64KHRPROC eglCreateSync64KHR;

    PFNEGLDEBUGMESSAGECONTROLKHRPROC eglDebugMessageControlKHR;
    PFNEGLQUERYDEBUGKHRPROC eglQueryDebugKHR;
    PFNEGLLABELOBJECTKHRPROC eglLabelObjectKHR;

    PFNEGLQUERYDISPLAYATTRIBKHRPROC eglQueryDisplayAttribKHR;

    PFNEGLCREATESYNCKHRPROC eglCreateSyncKHR;
    PFNEGLDESTROYSYNCKHRPROC eglDestroySyncKHR;
    PFNEGLCLIENTWAITSYNCKHRPROC eglClientWaitSyncKHR;
    PFNEGLGETSYNCATTRIBKHRPROC eglGetSyncAttribKHR;

    PFNEGLCREATEIMAGEKHRPROC eglCreateImageKHR;
    PFNEGLDESTROYIMAGEKHRPROC eglDestroyImageKHR;

    PFNEGLLOCKSURFACEKHRPROC eglLockSurfaceKHR;
    PFNEGLUNLOCKSURFACEKHRPROC eglUnlockSurfaceKHR;

    PFNEGLQUERYSURFACE64KHRPROC eglQuerySurface64KHR;

    PFNEGLSETDAMAGEREGIONKHRPROC eglSetDamageRegionKHR;

    PFNEGLSIGNALSYNCKHRPROC eglSignalSyncKHR;

    PFNEGLCREATESTREAMKHRPROC eglCreateStreamKHR;
    PFNEGLDESTROYSTREAMKHRPROC eglDestroyStreamKHR;
    PFNEGLSTREAMATTRIBKHRPROC eglStreamAttribKHR;
    PFNEGLQUERYSTREAMKHRPROC eglQueryStreamKHR;
    PFNEGLQUERYSTREAMU64KHRPROC eglQueryStreamu64KHR;

    PFNEGLCREATESTREAMATTRIBKHRPROC eglCreateStreamAttribKHR;
    PFNEGLSETSTREAMATTRIBKHRPROC eglSetStreamAttribKHR;
    PFNEGLQUERYSTREAMATTRIBKHRPROC eglQueryStreamAttribKHR;
    PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC eglStreamConsumerAcquireAttribKHR;
    PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC eglStreamConsumerReleaseAttribKHR;

    PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC eglStreamConsumerGLTextureExternalKHR;
    PFNEGLSTREAMCONSUMERACQUIREKHRPROC eglStreamConsumerAcquireKHR;
    PFNEGLSTREAMCONSUMERRELEASEKHRPROC eglStreamConsumerReleaseKHR;

    PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC eglGetStreamFileDescriptorKHR;
    PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC eglCreateStreamFromFileDescriptorKHR;

    PFNEGLQUERYSTREAMTIMEKHRPROC eglQueryStreamTimeKHR;

    PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC eglCreateStreamProducerSurfaceKHR;

    PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC eglSwapBuffersWithDamageKHR;

    PFNEGLWAITSYNCKHRPROC eglWaitSyncKHR;

    PFNEGLSETBLOBCACHEFUNCSANDROIDPROC eglSetBlobCacheFuncsANDROID;

    PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC eglCreateNativeClientBufferANDROID;

    PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC eglGetCompositorTimingSupportedANDROID;
    PFNEGLGETCOMPOSITORTIMINGANDROIDPROC eglGetCompositorTimingANDROID;
    PFNEGLGETNEXTFRAMEIDANDROIDPROC eglGetNextFrameIdANDROID;
    PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC eglGetFrameTimestampSupportedANDROID;
    PFNEGLGETFRAMETIMESTAMPSANDROIDPROC eglGetFrameTimestampsANDROID;

    PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC eglGetNativeClientBufferANDROID;

    PFNEGLDUPNATIVEFENCEFDANDROIDPROC eglDupNativeFenceFDANDROID;

    PFNEGLPRESENTATIONTIMEANDROIDPROC eglPresentationTimeANDROID;

    PFNEGLQUERYSURFACEPOINTERANGLEPROC eglQuerySurfacePointerANGLE;

    PFNEGLGETMSCRATEANGLEPROC eglGetMscRateANGLE;

    PFNEGLCLIENTSIGNALSYNCEXTPROC eglClientSignalSyncEXT;

    PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC eglCompositorSetContextListEXT;
    PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC eglCompositorSetContextAttributesEXT;
    PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC eglCompositorSetWindowListEXT;
    PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC eglCompositorSetWindowAttributesEXT;
    PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC eglCompositorBindTexWindowEXT;
    PFNEGLCOMPOSITORSETSIZEEXTPROC eglCompositorSetSizeEXT;
    PFNEGLCOMPOSITORSWAPPOLICYEXTPROC eglCompositorSwapPolicyEXT;

    PFNEGLQUERYDEVICEATTRIBEXTPROC eglQueryDeviceAttribEXT;
    PFNEGLQUERYDEVICESTRINGEXTPROC eglQueryDeviceStringEXT;
    PFNEGLQUERYDEVICESEXTPROC eglQueryDevicesEXT;
    PFNEGLQUERYDISPLAYATTRIBEXTPROC eglQueryDisplayAttribEXT;

    PFNEGLQUERYDEVICEBINARYEXTPROC eglQueryDeviceBinaryEXT;

    PFNEGLQUERYDMABUFFORMATSEXTPROC eglQueryDmaBufFormatsEXT;
    PFNEGLQUERYDMABUFMODIFIERSEXTPROC eglQueryDmaBufModifiersEXT;

    PFNEGLGETOUTPUTLAYERSEXTPROC eglGetOutputLayersEXT;
    PFNEGLGETOUTPUTPORTSEXTPROC eglGetOutputPortsEXT;
    PFNEGLOUTPUTLAYERATTRIBEXTPROC eglOutputLayerAttribEXT;
    PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC eglQueryOutputLayerAttribEXT;
    PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC eglQueryOutputLayerStringEXT;
    PFNEGLOUTPUTPORTATTRIBEXTPROC eglOutputPortAttribEXT;
    PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC eglQueryOutputPortAttribEXT;
    PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC eglQueryOutputPortStringEXT;

    PFNEGLGETPLATFORMDISPLAYEXTPROC eglGetPlatformDisplayEXT;
    PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC eglCreatePlatformWindowSurfaceEXT;
    PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC eglCreatePlatformPixmapSurfaceEXT;

    PFNEGLSTREAMCONSUMEROUTPUTEXTPROC eglStreamConsumerOutputEXT;

#if (EGL_EGLEXT_VERSION >= 20211210)
    PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC eglQuerySupportedCompressionRatesEXT;
#endif
    PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC eglSwapBuffersWithDamageEXT;

    PFNEGLUNSIGNALSYNCEXTPROC eglUnsignalSyncEXT;

    PFNEGLCREATEPIXMAPSURFACEHIPROC eglCreatePixmapSurfaceHI;

    PFNEGLCREATEDRMIMAGEMESAPROC eglCreateDRMImageMESA;
    PFNEGLEXPORTDRMIMAGEMESAPROC eglExportDRMImageMESA;

    PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC eglExportDMABUFImageQueryMESA;
    PFNEGLEXPORTDMABUFIMAGEMESAPROC eglExportDMABUFImageMESA;

    PFNEGLGETDISPLAYDRIVERCONFIGPROC eglGetDisplayDriverConfig;
    PFNEGLGETDISPLAYDRIVERNAMEPROC eglGetDisplayDriverName;

    PFNEGLSWAPBUFFERSREGIONNOKPROC eglSwapBuffersRegionNOK;

    PFNEGLSWAPBUFFERSREGION2NOKPROC eglSwapBuffersRegion2NOK;

    PFNEGLQUERYNATIVEDISPLAYNVPROC eglQueryNativeDisplayNV;
    PFNEGLQUERYNATIVEWINDOWNVPROC eglQueryNativeWindowNV;
    PFNEGLQUERYNATIVEPIXMAPNVPROC eglQueryNativePixmapNV;

    PFNEGLPOSTSUBBUFFERNVPROC eglPostSubBufferNV;

    PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC eglStreamImageConsumerConnectNV;
    PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC eglQueryStreamConsumerEventNV;
    PFNEGLSTREAMACQUIREIMAGENVPROC eglStreamAcquireImageNV;
    PFNEGLSTREAMRELEASEIMAGENVPROC eglStreamReleaseImageNV;

    PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC eglStreamConsumerGLTextureExternalAttribsNV;

    PFNEGLSTREAMFLUSHNVPROC eglStreamFlushNV;

    PFNEGLQUERYDISPLAYATTRIBNVPROC eglQueryDisplayAttribNV;
    PFNEGLSETSTREAMMETADATANVPROC eglSetStreamMetadataNV;
    PFNEGLQUERYSTREAMMETADATANVPROC eglQueryStreamMetadataNV;

    PFNEGLRESETSTREAMNVPROC eglResetStreamNV;

    PFNEGLCREATESTREAMSYNCNVPROC eglCreateStreamSyncNV;

    PFNEGLCREATEFENCESYNCNVPROC eglCreateFenceSyncNV;
    PFNEGLDESTROYSYNCNVPROC eglDestroySyncNV;
    PFNEGLFENCENVPROC eglFenceNV;
    PFNEGLCLIENTWAITSYNCNVPROC eglClientWaitSyncNV;
    PFNEGLSIGNALSYNCNVPROC eglSignalSyncNV;
    PFNEGLGETSYNCATTRIBNVPROC eglGetSyncAttribNV;

    PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC eglGetSystemTimeFrequencyNV;
    PFNEGLGETSYSTEMTIMENVPROC eglGetSystemTimeNV;

    PFNEGLBINDWAYLANDDISPLAYWLPROC eglBindWaylandDisplayWL;
    PFNEGLUNBINDWAYLANDDISPLAYWLPROC eglUnbindWaylandDisplayWL;
    PFNEGLQUERYWAYLANDBUFFERWLPROC eglQueryWaylandBufferWL;

    PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC eglCreateWaylandBufferFromImageWL;
};

struct eglext_functions functions;

void eglext_load()
{
    (void)memset(&functions, 0, sizeof(struct eglext_functions));

    LOAD_FUNCTION(PFNEGLCREATESYNC64KHRPROC, eglCreateSync64KHR);

    LOAD_FUNCTION(PFNEGLDEBUGMESSAGECONTROLKHRPROC, eglDebugMessageControlKHR);
    LOAD_FUNCTION(PFNEGLQUERYDEBUGKHRPROC, eglQueryDebugKHR);
    LOAD_FUNCTION(PFNEGLLABELOBJECTKHRPROC, eglLabelObjectKHR);

    LOAD_FUNCTION(PFNEGLQUERYDISPLAYATTRIBKHRPROC, eglQueryDisplayAttribKHR);

    LOAD_FUNCTION(PFNEGLCREATESYNCKHRPROC, eglCreateSyncKHR);
    LOAD_FUNCTION(PFNEGLDESTROYSYNCKHRPROC, eglDestroySyncKHR);
    LOAD_FUNCTION(PFNEGLCLIENTWAITSYNCKHRPROC, eglClientWaitSyncKHR);
    LOAD_FUNCTION(PFNEGLGETSYNCATTRIBKHRPROC, eglGetSyncAttribKHR);

    LOAD_FUNCTION(PFNEGLCREATEIMAGEKHRPROC, eglCreateImageKHR);
    LOAD_FUNCTION(PFNEGLDESTROYIMAGEKHRPROC, eglDestroyImageKHR);

    LOAD_FUNCTION(PFNEGLLOCKSURFACEKHRPROC, eglLockSurfaceKHR);
    LOAD_FUNCTION(PFNEGLUNLOCKSURFACEKHRPROC, eglUnlockSurfaceKHR);

    LOAD_FUNCTION(PFNEGLQUERYSURFACE64KHRPROC, eglQuerySurface64KHR);

    LOAD_FUNCTION(PFNEGLSETDAMAGEREGIONKHRPROC, eglSetDamageRegionKHR);

    LOAD_FUNCTION(PFNEGLSIGNALSYNCKHRPROC, eglSignalSyncKHR);

    LOAD_FUNCTION(PFNEGLCREATESTREAMKHRPROC, eglCreateStreamKHR);
    LOAD_FUNCTION(PFNEGLDESTROYSTREAMKHRPROC, eglDestroyStreamKHR);
    LOAD_FUNCTION(PFNEGLSTREAMATTRIBKHRPROC, eglStreamAttribKHR);
    LOAD_FUNCTION(PFNEGLQUERYSTREAMKHRPROC, eglQueryStreamKHR);
    LOAD_FUNCTION(PFNEGLQUERYSTREAMU64KHRPROC, eglQueryStreamu64KHR);

    LOAD_FUNCTION(PFNEGLCREATESTREAMATTRIBKHRPROC, eglCreateStreamAttribKHR);
    LOAD_FUNCTION(PFNEGLSETSTREAMATTRIBKHRPROC, eglSetStreamAttribKHR);
    LOAD_FUNCTION(PFNEGLQUERYSTREAMATTRIBKHRPROC, eglQueryStreamAttribKHR);
    LOAD_FUNCTION(PFNEGLSTREAMCONSUMERACQUIREATTRIBKHRPROC, eglStreamConsumerAcquireAttribKHR);
    LOAD_FUNCTION(PFNEGLSTREAMCONSUMERRELEASEATTRIBKHRPROC, eglStreamConsumerReleaseAttribKHR);

    LOAD_FUNCTION(PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALKHRPROC, eglStreamConsumerGLTextureExternalKHR);
    LOAD_FUNCTION(PFNEGLSTREAMCONSUMERACQUIREKHRPROC, eglStreamConsumerAcquireKHR);
    LOAD_FUNCTION(PFNEGLSTREAMCONSUMERRELEASEKHRPROC, eglStreamConsumerReleaseKHR);

    LOAD_FUNCTION(PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC, eglGetStreamFileDescriptorKHR);
    LOAD_FUNCTION(PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC, eglCreateStreamFromFileDescriptorKHR);

    LOAD_FUNCTION(PFNEGLQUERYSTREAMTIMEKHRPROC, eglQueryStreamTimeKHR);

    LOAD_FUNCTION(PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC, eglCreateStreamProducerSurfaceKHR);

    LOAD_FUNCTION(PFNEGLSWAPBUFFERSWITHDAMAGEKHRPROC, eglSwapBuffersWithDamageKHR);

    LOAD_FUNCTION(PFNEGLWAITSYNCKHRPROC, eglWaitSyncKHR);

    LOAD_FUNCTION(PFNEGLSETBLOBCACHEFUNCSANDROIDPROC, eglSetBlobCacheFuncsANDROID);

    LOAD_FUNCTION(PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC, eglCreateNativeClientBufferANDROID);

    LOAD_FUNCTION(PFNEGLGETCOMPOSITORTIMINGSUPPORTEDANDROIDPROC, eglGetCompositorTimingSupportedANDROID);
    LOAD_FUNCTION(PFNEGLGETCOMPOSITORTIMINGANDROIDPROC, eglGetCompositorTimingANDROID);
    LOAD_FUNCTION(PFNEGLGETNEXTFRAMEIDANDROIDPROC, eglGetNextFrameIdANDROID);
    LOAD_FUNCTION(PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC, eglGetFrameTimestampSupportedANDROID);
    LOAD_FUNCTION(PFNEGLGETFRAMETIMESTAMPSANDROIDPROC, eglGetFrameTimestampsANDROID);

    LOAD_FUNCTION(PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC, eglGetNativeClientBufferANDROID);

    LOAD_FUNCTION(PFNEGLDUPNATIVEFENCEFDANDROIDPROC, eglDupNativeFenceFDANDROID);

    LOAD_FUNCTION(PFNEGLPRESENTATIONTIMEANDROIDPROC, eglPresentationTimeANDROID);

    LOAD_FUNCTION(PFNEGLQUERYSURFACEPOINTERANGLEPROC, eglQuerySurfacePointerANGLE);

    LOAD_FUNCTION(PFNEGLGETMSCRATEANGLEPROC, eglGetMscRateANGLE);

    LOAD_FUNCTION(PFNEGLCLIENTSIGNALSYNCEXTPROC, eglClientSignalSyncEXT);

    LOAD_FUNCTION(PFNEGLCOMPOSITORSETCONTEXTLISTEXTPROC, eglCompositorSetContextListEXT);
    LOAD_FUNCTION(PFNEGLCOMPOSITORSETCONTEXTATTRIBUTESEXTPROC, eglCompositorSetContextAttributesEXT);
    LOAD_FUNCTION(PFNEGLCOMPOSITORSETWINDOWLISTEXTPROC, eglCompositorSetWindowListEXT);
    LOAD_FUNCTION(PFNEGLCOMPOSITORSETWINDOWATTRIBUTESEXTPROC, eglCompositorSetWindowAttributesEXT);
    LOAD_FUNCTION(PFNEGLCOMPOSITORBINDTEXWINDOWEXTPROC, eglCompositorBindTexWindowEXT);
    LOAD_FUNCTION(PFNEGLCOMPOSITORSETSIZEEXTPROC, eglCompositorSetSizeEXT);
    LOAD_FUNCTION(PFNEGLCOMPOSITORSWAPPOLICYEXTPROC, eglCompositorSwapPolicyEXT);

    LOAD_FUNCTION(PFNEGLQUERYDEVICEATTRIBEXTPROC, eglQueryDeviceAttribEXT);
    LOAD_FUNCTION(PFNEGLQUERYDEVICESTRINGEXTPROC, eglQueryDeviceStringEXT);
    LOAD_FUNCTION(PFNEGLQUERYDEVICESEXTPROC, eglQueryDevicesEXT);
    LOAD_FUNCTION(PFNEGLQUERYDISPLAYATTRIBEXTPROC, eglQueryDisplayAttribEXT);

    LOAD_FUNCTION(PFNEGLQUERYDEVICEBINARYEXTPROC, eglQueryDeviceBinaryEXT);

    LOAD_FUNCTION(PFNEGLQUERYDMABUFFORMATSEXTPROC, eglQueryDmaBufFormatsEXT);
    LOAD_FUNCTION(PFNEGLQUERYDMABUFMODIFIERSEXTPROC, eglQueryDmaBufModifiersEXT);

    LOAD_FUNCTION(PFNEGLGETOUTPUTLAYERSEXTPROC, eglGetOutputLayersEXT);
    LOAD_FUNCTION(PFNEGLGETOUTPUTPORTSEXTPROC, eglGetOutputPortsEXT);
    LOAD_FUNCTION(PFNEGLOUTPUTLAYERATTRIBEXTPROC, eglOutputLayerAttribEXT);
    LOAD_FUNCTION(PFNEGLQUERYOUTPUTLAYERATTRIBEXTPROC, eglQueryOutputLayerAttribEXT);
    LOAD_FUNCTION(PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC, eglQueryOutputLayerStringEXT);
    LOAD_FUNCTION(PFNEGLOUTPUTPORTATTRIBEXTPROC, eglOutputPortAttribEXT);
    LOAD_FUNCTION(PFNEGLQUERYOUTPUTPORTATTRIBEXTPROC, eglQueryOutputPortAttribEXT);
    LOAD_FUNCTION(PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC, eglQueryOutputPortStringEXT);

    LOAD_FUNCTION(PFNEGLGETPLATFORMDISPLAYEXTPROC, eglGetPlatformDisplayEXT);
    LOAD_FUNCTION(PFNEGLCREATEPLATFORMWINDOWSURFACEEXTPROC, eglCreatePlatformWindowSurfaceEXT);
    LOAD_FUNCTION(PFNEGLCREATEPLATFORMPIXMAPSURFACEEXTPROC, eglCreatePlatformPixmapSurfaceEXT);

    LOAD_FUNCTION(PFNEGLSTREAMCONSUMEROUTPUTEXTPROC, eglStreamConsumerOutputEXT);
#if (EGL_EGLEXT_VERSION >= 20211210)
    LOAD_FUNCTION(PFNEGLQUERYSUPPORTEDCOMPRESSIONRATESEXTPROC, eglQuerySupportedCompressionRatesEXT);
#endif
    LOAD_FUNCTION(PFNEGLSWAPBUFFERSWITHDAMAGEEXTPROC, eglSwapBuffersWithDamageEXT);

    LOAD_FUNCTION(PFNEGLUNSIGNALSYNCEXTPROC, eglUnsignalSyncEXT);

    LOAD_FUNCTION(PFNEGLCREATEPIXMAPSURFACEHIPROC, eglCreatePixmapSurfaceHI);

    LOAD_FUNCTION(PFNEGLCREATEDRMIMAGEMESAPROC, eglCreateDRMImageMESA);
    LOAD_FUNCTION(PFNEGLEXPORTDRMIMAGEMESAPROC, eglExportDRMImageMESA);

    LOAD_FUNCTION(PFNEGLEXPORTDMABUFIMAGEQUERYMESAPROC, eglExportDMABUFImageQueryMESA);
    LOAD_FUNCTION(PFNEGLEXPORTDMABUFIMAGEMESAPROC, eglExportDMABUFImageMESA);

    LOAD_FUNCTION(PFNEGLGETDISPLAYDRIVERCONFIGPROC, eglGetDisplayDriverConfig);
    LOAD_FUNCTION(PFNEGLGETDISPLAYDRIVERNAMEPROC, eglGetDisplayDriverName);

    LOAD_FUNCTION(PFNEGLSWAPBUFFERSREGIONNOKPROC, eglSwapBuffersRegionNOK);

    LOAD_FUNCTION(PFNEGLSWAPBUFFERSREGION2NOKPROC, eglSwapBuffersRegion2NOK);

    LOAD_FUNCTION(PFNEGLQUERYNATIVEDISPLAYNVPROC, eglQueryNativeDisplayNV);
    LOAD_FUNCTION(PFNEGLQUERYNATIVEWINDOWNVPROC, eglQueryNativeWindowNV);
    LOAD_FUNCTION(PFNEGLQUERYNATIVEPIXMAPNVPROC, eglQueryNativePixmapNV);

    LOAD_FUNCTION(PFNEGLPOSTSUBBUFFERNVPROC, eglPostSubBufferNV);

    LOAD_FUNCTION(PFNEGLSTREAMIMAGECONSUMERCONNECTNVPROC, eglStreamImageConsumerConnectNV);
    LOAD_FUNCTION(PFNEGLQUERYSTREAMCONSUMEREVENTNVPROC, eglQueryStreamConsumerEventNV);
    LOAD_FUNCTION(PFNEGLSTREAMACQUIREIMAGENVPROC, eglStreamAcquireImageNV);
    LOAD_FUNCTION(PFNEGLSTREAMRELEASEIMAGENVPROC, eglStreamReleaseImageNV);

    LOAD_FUNCTION(PFNEGLSTREAMCONSUMERGLTEXTUREEXTERNALATTRIBSNVPROC, eglStreamConsumerGLTextureExternalAttribsNV);

    LOAD_FUNCTION(PFNEGLSTREAMFLUSHNVPROC, eglStreamFlushNV);

    LOAD_FUNCTION(PFNEGLQUERYDISPLAYATTRIBNVPROC, eglQueryDisplayAttribNV);
    LOAD_FUNCTION(PFNEGLSETSTREAMMETADATANVPROC, eglSetStreamMetadataNV);
    LOAD_FUNCTION(PFNEGLQUERYSTREAMMETADATANVPROC, eglQueryStreamMetadataNV);

    LOAD_FUNCTION(PFNEGLRESETSTREAMNVPROC, eglResetStreamNV);

    LOAD_FUNCTION(PFNEGLCREATESTREAMSYNCNVPROC, eglCreateStreamSyncNV);

    LOAD_FUNCTION(PFNEGLCREATEFENCESYNCNVPROC, eglCreateFenceSyncNV);
    LOAD_FUNCTION(PFNEGLDESTROYSYNCNVPROC, eglDestroySyncNV);
    LOAD_FUNCTION(PFNEGLFENCENVPROC, eglFenceNV);
    LOAD_FUNCTION(PFNEGLCLIENTWAITSYNCNVPROC, eglClientWaitSyncNV);
    LOAD_FUNCTION(PFNEGLSIGNALSYNCNVPROC, eglSignalSyncNV);
    LOAD_FUNCTION(PFNEGLGETSYNCATTRIBNVPROC, eglGetSyncAttribNV);

    LOAD_FUNCTION(PFNEGLGETSYSTEMTIMEFREQUENCYNVPROC, eglGetSystemTimeFrequencyNV);
    LOAD_FUNCTION(PFNEGLGETSYSTEMTIMENVPROC, eglGetSystemTimeNV);

    LOAD_FUNCTION(PFNEGLBINDWAYLANDDISPLAYWLPROC, eglBindWaylandDisplayWL);
    LOAD_FUNCTION(PFNEGLUNBINDWAYLANDDISPLAYWLPROC, eglUnbindWaylandDisplayWL);
    LOAD_FUNCTION(PFNEGLQUERYWAYLANDBUFFERWLPROC, eglQueryWaylandBufferWL);

    LOAD_FUNCTION(PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC, eglCreateWaylandBufferFromImageWL);
}

EGLAPI EGLSyncKHR EGLAPIENTRY eglCreateSync64KHR(EGLDisplay dpy, EGLenum type, const EGLAttribKHR *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLSyncKHR, EGL_NO_SYNC_KHR, eglCreateSync64KHR, dpy, type, attrib_list);
}

EGLAPI EGLint EGLAPIENTRY eglDebugMessageControlKHR(EGLDEBUGPROCKHR callback, const EGLAttrib *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLint, -1, eglDebugMessageControlKHR, callback, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQueryDebugKHR(EGLint attribute, EGLAttrib *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQueryDebugKHR, attribute, value);
}

EGLAPI EGLint EGLAPIENTRY eglLabelObjectKHR(EGLDisplay display, EGLenum objectType, EGLObjectKHR object, EGLLabelKHR label)
{
    IMPLEMENT_FUNCTION(EGLint, -1, eglLabelObjectKHR, display, objectType, object, label);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQueryDisplayAttribKHR(EGLDisplay dpy, EGLint name, EGLAttrib *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQueryDisplayAttribKHR, dpy, name, value);
}

EGLAPI EGLSyncKHR EGLAPIENTRY eglCreateSyncKHR(EGLDisplay dpy, EGLenum type, const EGLint *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLSyncKHR, NULL, eglCreateSyncKHR, dpy, type, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglDestroySyncKHR(EGLDisplay dpy, EGLSyncKHR sync)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglDestroySyncKHR, dpy, sync);
}

EGLAPI EGLint EGLAPIENTRY eglClientWaitSyncKHR(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout)
{
    IMPLEMENT_FUNCTION(EGLint, -1, eglClientWaitSyncKHR, dpy, sync, flags, timeout);
}

EGLAPI EGLBoolean EGLAPIENTRY eglGetSyncAttribKHR(EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglGetSyncAttribKHR, dpy, sync, attribute, value);
}

EGLAPI EGLImageKHR EGLAPIENTRY eglCreateImageKHR(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLint *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLImageKHR, EGL_NO_IMAGE_KHR, eglCreateImageKHR, dpy, ctx, target, buffer, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglDestroyImageKHR(EGLDisplay dpy, EGLImageKHR image)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglDestroyImageKHR, dpy, image);
}

EGLAPI EGLBoolean EGLAPIENTRY eglLockSurfaceKHR(EGLDisplay dpy, EGLSurface surface, const EGLint *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglLockSurfaceKHR, dpy, surface, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglUnlockSurfaceKHR(EGLDisplay dpy, EGLSurface surface)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglUnlockSurfaceKHR, dpy, surface);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQuerySurface64KHR(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLAttribKHR *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQuerySurface64KHR, dpy, surface, attribute, value);
}

EGLAPI EGLBoolean EGLAPIENTRY eglSetDamageRegionKHR(EGLDisplay dpy, EGLSurface surface, EGLint *rects, EGLint n_rects)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglSetDamageRegionKHR, dpy, surface, rects, n_rects);
}

EGLAPI EGLBoolean EGLAPIENTRY eglSignalSyncKHR(EGLDisplay dpy, EGLSyncKHR sync, EGLenum mode)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglSignalSyncKHR, dpy, sync, mode);
}

EGLAPI EGLStreamKHR EGLAPIENTRY eglCreateStreamKHR(EGLDisplay dpy, const EGLint *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLStreamKHR, NULL, eglCreateStreamKHR, dpy, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglDestroyStreamKHR(EGLDisplay dpy, EGLStreamKHR stream)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglDestroyStreamKHR, dpy, stream);
}

EGLAPI EGLBoolean EGLAPIENTRY eglStreamAttribKHR(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglStreamAttribKHR, dpy, stream, attribute, value);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQueryStreamKHR(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQueryStreamKHR, dpy, stream, attribute, value);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQueryStreamu64KHR(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLuint64KHR *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQueryStreamu64KHR, dpy, stream, attribute, value);
}

EGLAPI EGLStreamKHR EGLAPIENTRY eglCreateStreamAttribKHR(EGLDisplay dpy, const EGLAttrib *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLStreamKHR, NULL, eglCreateStreamAttribKHR, dpy, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglSetStreamAttribKHR(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglSetStreamAttribKHR, dpy, stream, attribute, value);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQueryStreamAttribKHR(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQueryStreamAttribKHR, dpy, stream, attribute, value);
}

EGLAPI EGLBoolean EGLAPIENTRY eglStreamConsumerAcquireAttribKHR(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglStreamConsumerAcquireAttribKHR, dpy, stream, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglStreamConsumerReleaseAttribKHR(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglStreamConsumerReleaseAttribKHR, dpy, stream, attrib_list);
}

EGLAPI EGLBoolean EGLAPIENTRY eglStreamConsumerGLTextureExternalKHR(EGLDisplay dpy, EGLStreamKHR stream)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglStreamConsumerGLTextureExternalKHR, dpy, stream);
}

EGLAPI EGLBoolean EGLAPIENTRY eglStreamConsumerAcquireKHR(EGLDisplay dpy, EGLStreamKHR stream)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglStreamConsumerAcquireKHR, dpy, stream);
}

EGLAPI EGLBoolean EGLAPIENTRY eglStreamConsumerReleaseKHR(EGLDisplay dpy, EGLStreamKHR stream)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglStreamConsumerReleaseKHR, dpy, stream);
}

EGLAPI EGLNativeFileDescriptorKHR EGLAPIENTRY eglGetStreamFileDescriptorKHR(EGLDisplay dpy, EGLStreamKHR stream)
{
    IMPLEMENT_FUNCTION(EGLNativeFileDescriptorKHR, EGL_NO_FILE_DESCRIPTOR_KHR, eglGetStreamFileDescriptorKHR, dpy, stream);
}

EGLAPI EGLStreamKHR EGLAPIENTRY eglCreateStreamFromFileDescriptorKHR(EGLDisplay dpy, EGLNativeFileDescriptorKHR file_descriptor)
{
    IMPLEMENT_FUNCTION(EGLStreamKHR, NULL, eglCreateStreamFromFileDescriptorKHR, dpy, file_descriptor);
}

EGLAPI EGLBoolean EGLAPIENTRY eglQueryStreamTimeKHR(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLTimeKHR *value)
{
    IMPLEMENT_FUNCTION(EGLBoolean, EGL_FALSE, eglQueryStreamTimeKHR, dpy, stream, attribute, value);
}

EGLAPI EGLSurface EGLAPIENTRY eglCreateStreamProducerSurfaceKHR(EGLDisplay dpy, EGLConfig config, EGLStreamKHR stream, const EGLint *attrib_list)
{
    IMPLEMENT_FUNCTION(EGLSurface, EGL_NO_SURFACE, eglCreateStreamProducerSurfaceKHR, dpy, config, stream, attrib_list);
}

